# Generated by Django 5.1.4 on 2026-08-11 09:09

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('working_days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=list, help_text='Days of the week (0=Monday ... 6=Sunday) that count toward leave-day calculations.', size=None)),
                ('pending_approval_urgency_days', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('audit_log_display_limit', models.PositiveIntegerField(default=200, validators=[django.core.validators.MinValueValidator(1)])),
                ('session_max_age_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
