import type {
  AppSettings,
  Department,
  Employee,
  Holiday,
  LeaveBalance,
  LeaveRequest,
  LeaveType,
  OnboardingChecklist,
  OnboardingResource,
  OnboardingTask,
} from "@/types";

export const departments: Department[] = [
  { id: "dept-eng", name: "Engineering" },
  { id: "dept-sales", name: "Sales" },
  { id: "dept-people", name: "People Ops" },
];

export const defaultSettings: AppSettings = {
  workingDays: [1, 2, 3, 4, 5],
  upcomingLeaveWindowDays: 30,
  pendingApprovalUrgencyDays: 3,
  auditLogDisplayLimit: 200,
  sessionMaxAgeDays: 30,
};

// Every seeded account already has this password ("Agrileaf@123") so the app is fully explorable
// right after `docker compose up -d --build`, without needing to read an invitation email for each
// role. Generated once via hashPassword("Agrileaf@123") — see src/lib/password.ts for the scheme.
export const DEMO_PASSWORD_HASH =
  "59a2c713a9d0fa79265c3ea6ab154bba:c6ea9f603195e32a05b1e9fd85c9c9b3b7dc1a8dfb7e4e9f2b1b702a729c802f2664b1e78829770ce5f6345bb54ffb47b6cf49a85bedc7b23240815fb3f7a981";

// Distinct from `Employee` (the create/update payload shape used everywhere else) since seeding is
// the one place that legitimately writes password_hash directly, bypassing the normal invite flow.
type SeedEmployee = Employee & { passwordHash: string };

export const employees: SeedEmployee[] = [
  {
    id: "emp-aditi",
    name: "Aditi Rao",
    email: "aditi.rao@agrileaf.in",
    avatarUrl: null,
    role: "ADMIN",
    title: "Head of People Ops",
    departmentId: "dept-people",
    managerId: null,
    joinedAt: "2019-03-11",
    status: "ACTIVE",
    onboardingChecklistId: null,
    passwordHash: DEMO_PASSWORD_HASH,
  },
  {
    id: "emp-neha",
    name: "Neha Kapoor",
    email: "neha.kapoor@agrileaf.in",
    avatarUrl: null,
    role: "MANAGER",
    title: "Engineering Manager",
    departmentId: "dept-eng",
    managerId: "emp-aditi",
    joinedAt: "2020-06-01",
    status: "ACTIVE",
    onboardingChecklistId: null,
    passwordHash: DEMO_PASSWORD_HASH,
  },
  {
    id: "emp-rahul",
    name: "Rahul Mehta",
    email: "rahul.mehta@agrileaf.in",
    avatarUrl: null,
    role: "EMPLOYEE",
    title: "Senior Software Engineer",
    departmentId: "dept-eng",
    managerId: "emp-neha",
    joinedAt: "2021-01-18",
    status: "ACTIVE",
    onboardingChecklistId: null,
    passwordHash: DEMO_PASSWORD_HASH,
  },
  {
    id: "emp-sana",
    name: "Sana Iyer",
    email: "sana.iyer@agrileaf.in",
    avatarUrl: null,
    role: "EMPLOYEE",
    title: "Software Engineer",
    departmentId: "dept-eng",
    managerId: "emp-neha",
    joinedAt: "2022-08-22",
    status: "ACTIVE",
    onboardingChecklistId: null,
    passwordHash: DEMO_PASSWORD_HASH,
  },
  {
    id: "emp-arjun",
    name: "Arjun Verma",
    email: "arjun.verma@agrileaf.in",
    avatarUrl: null,
    role: "EMPLOYEE",
    title: "QA Engineer",
    departmentId: "dept-eng",
    managerId: "emp-neha",
    joinedAt: "2023-02-13",
    status: "ACTIVE",
    onboardingChecklistId: "checklist-eng",
    passwordHash: DEMO_PASSWORD_HASH,
  },
  {
    id: "emp-priya",
    name: "Priya Nair",
    email: "priya.nair@agrileaf.in",
    avatarUrl: null,
    role: "MANAGER",
    title: "Sales Manager",
    departmentId: "dept-sales",
    managerId: "emp-aditi",
    joinedAt: "2020-11-09",
    status: "ACTIVE",
    onboardingChecklistId: null,
    passwordHash: DEMO_PASSWORD_HASH,
  },
  {
    id: "emp-vikram",
    name: "Vikram Singh",
    email: "vikram.singh@agrileaf.in",
    avatarUrl: null,
    role: "EMPLOYEE",
    title: "Account Executive",
    departmentId: "dept-sales",
    managerId: "emp-priya",
    joinedAt: "2023-05-30",
    status: "ACTIVE",
    onboardingChecklistId: "checklist-sales",
    passwordHash: DEMO_PASSWORD_HASH,
  },
];

export const leaveTypes: LeaveType[] = [
  {
    id: "lt-casual",
    name: "Casual Leave",
    code: "CL",
    color: "#2563eb",
    defaultDaysPerYear: 12,
    requiresApproval: true,
    isActive: true,
    accrualMethod: "ANNUAL",
    carryForwardLimit: 5,
  },
  {
    id: "lt-sick",
    name: "Sick Leave",
    code: "SL",
    color: "#dc2626",
    defaultDaysPerYear: 10,
    requiresApproval: true,
    isActive: true,
    accrualMethod: "ANNUAL",
    carryForwardLimit: 0,
  },
  {
    id: "lt-earned",
    name: "Earned Leave",
    code: "EL",
    color: "#16a34a",
    defaultDaysPerYear: 15,
    requiresApproval: true,
    isActive: true,
    accrualMethod: "ANNUAL",
    carryForwardLimit: 10,
  },
  {
    id: "lt-wfh",
    name: "Work From Home",
    code: "WFH",
    color: "#7c3aed",
    defaultDaysPerYear: 24,
    requiresApproval: true,
    isActive: true,
    accrualMethod: "MONTHLY",
    carryForwardLimit: 0,
  },
  {
    id: "lt-unpaid",
    name: "Unpaid Leave",
    code: "LWP",
    color: "#525252",
    defaultDaysPerYear: 0,
    requiresApproval: true,
    isActive: true,
    accrualMethod: "ANNUAL",
    carryForwardLimit: 0,
  },
];

export const holidays: Holiday[] = [
  { id: "hol-1", name: "Republic Day", date: "2026-01-26", optional: false },
  { id: "hol-2", name: "Holi", date: "2026-03-04", optional: false },
  { id: "hol-3", name: "Good Friday", date: "2026-04-03", optional: true },
  { id: "hol-4", name: "Independence Day", date: "2026-08-15", optional: false },
  { id: "hol-5", name: "Ganesh Chaturthi", date: "2026-09-14", optional: true },
  { id: "hol-6", name: "Gandhi Jayanti", date: "2026-10-02", optional: false },
  { id: "hol-7", name: "Diwali", date: "2026-11-08", optional: false },
  { id: "hol-8", name: "Christmas", date: "2026-12-25", optional: false },
];

function balance(employeeId: string, leaveTypeId: string, allocated: number, used: number): LeaveBalance {
  // Computed at seed time (this only ever runs once, against an empty database — see
  // seedIfEmpty in db/seed.ts) rather than hardcoded, so a demo environment started in any year
  // gets a balance row for that same year, matching what the real app looks up for "now".
  return { employeeId, leaveTypeId, year: new Date().getFullYear(), allocated, used, carriedForward: 0 };
}

export const leaveBalances: LeaveBalance[] = employees.flatMap((emp) => [
  balance(emp.id, "lt-casual", 12, emp.id === "emp-rahul" ? 4 : emp.id === "emp-sana" ? 2 : 1),
  balance(emp.id, "lt-sick", 10, emp.id === "emp-vikram" ? 3 : 1),
  balance(emp.id, "lt-earned", 15, emp.id === "emp-neha" ? 5 : 2),
  balance(emp.id, "lt-wfh", 24, emp.id === "emp-arjun" ? 6 : 3),
  balance(emp.id, "lt-unpaid", 0, 0),
]);

export const leaveRequests: LeaveRequest[] = [
  {
    id: "lr-1",
    referenceNumber: "LR-2026-0001",
    employeeId: "emp-rahul",
    leaveTypeId: "lt-casual",
    startDate: "2026-08-12",
    endDate: "2026-08-13",
    days: 2,
    reason: "Family function out of town.",
    status: "PENDING",
    approverId: "emp-neha",
    approverComment: null,
    appliedAt: "2026-08-04T09:12:00.000Z",
    decidedAt: null,
  },
  {
    id: "lr-2",
    referenceNumber: "LR-2026-0002",
    employeeId: "emp-sana",
    leaveTypeId: "lt-sick",
    startDate: "2026-08-05",
    endDate: "2026-08-05",
    days: 1,
    reason: "Fever, resting at home.",
    status: "PENDING",
    approverId: "emp-neha",
    approverComment: null,
    appliedAt: "2026-08-05T07:40:00.000Z",
    decidedAt: null,
  },
  {
    id: "lr-3",
    referenceNumber: "LR-2026-0003",
    employeeId: "emp-arjun",
    leaveTypeId: "lt-wfh",
    startDate: "2026-07-21",
    endDate: "2026-07-25",
    days: 5,
    reason: "Home internet installation and a few personal errands.",
    status: "APPROVED",
    approverId: "emp-neha",
    approverComment: "Approved, please stay reachable on chat.",
    appliedAt: "2026-07-15T11:05:00.000Z",
    decidedAt: "2026-07-15T15:22:00.000Z",
  },
  {
    id: "lr-4",
    referenceNumber: "LR-2026-0004",
    employeeId: "emp-rahul",
    leaveTypeId: "lt-earned",
    startDate: "2026-06-01",
    endDate: "2026-06-05",
    days: 3,
    reason: "Family trip.",
    status: "REJECTED",
    approverId: "emp-neha",
    approverComment: "Release week for the mobile app, please pick another week.",
    appliedAt: "2026-05-20T10:00:00.000Z",
    decidedAt: "2026-05-21T09:30:00.000Z",
  },
  {
    id: "lr-5",
    referenceNumber: "LR-2026-0005",
    employeeId: "emp-vikram",
    leaveTypeId: "lt-casual",
    startDate: "2026-08-20",
    endDate: "2026-08-21",
    days: 2,
    reason: "Personal work.",
    status: "PENDING",
    approverId: "emp-priya",
    approverComment: null,
    appliedAt: "2026-08-06T08:00:00.000Z",
    decidedAt: null,
  },
  {
    id: "lr-6",
    referenceNumber: "LR-2026-0006",
    employeeId: "emp-neha",
    leaveTypeId: "lt-earned",
    startDate: "2026-04-10",
    endDate: "2026-04-14",
    days: 3,
    reason: "Vacation.",
    status: "CANCELLED",
    approverId: "emp-aditi",
    approverComment: null,
    appliedAt: "2026-03-28T12:00:00.000Z",
    decidedAt: null,
  },
  {
    id: "lr-7",
    referenceNumber: "LR-2026-0007",
    employeeId: "emp-neha",
    leaveTypeId: "lt-wfh",
    startDate: "2026-02-09",
    endDate: "2026-02-10",
    days: 2,
    reason: "Broadband upgrade at home.",
    status: "APPROVED",
    approverId: "emp-aditi",
    approverComment: "Approved.",
    appliedAt: "2026-02-02T09:00:00.000Z",
    decidedAt: "2026-02-02T14:00:00.000Z",
  },
  {
    id: "lr-8",
    referenceNumber: "LR-2026-0008",
    employeeId: "emp-vikram",
    leaveTypeId: "lt-sick",
    startDate: "2026-02-17",
    endDate: "2026-02-17",
    days: 1,
    reason: "Down with flu.",
    status: "APPROVED",
    approverId: "emp-priya",
    approverComment: "Get well soon.",
    appliedAt: "2026-02-17T08:10:00.000Z",
    decidedAt: "2026-02-17T08:45:00.000Z",
  },
  {
    id: "lr-9",
    referenceNumber: "LR-2026-0009",
    employeeId: "emp-sana",
    leaveTypeId: "lt-wfh",
    startDate: "2026-02-24",
    endDate: "2026-02-25",
    days: 2,
    reason: "Internet installation at new place.",
    status: "APPROVED",
    approverId: "emp-neha",
    approverComment: "Approved.",
    appliedAt: "2026-02-19T10:30:00.000Z",
    decidedAt: "2026-02-20T09:00:00.000Z",
  },
  {
    id: "lr-10",
    referenceNumber: "LR-2026-0010",
    employeeId: "emp-rahul",
    leaveTypeId: "lt-casual",
    startDate: "2026-03-09",
    endDate: "2026-03-10",
    days: 2,
    reason: "Cousin's wedding.",
    status: "APPROVED",
    approverId: "emp-neha",
    approverComment: "Approved, have fun.",
    appliedAt: "2026-02-24T11:00:00.000Z",
    decidedAt: "2026-02-26T09:15:00.000Z",
  },
  {
    id: "lr-11",
    referenceNumber: "LR-2026-0011",
    employeeId: "emp-priya",
    leaveTypeId: "lt-earned",
    startDate: "2026-03-16",
    endDate: "2026-03-19",
    days: 4,
    reason: "Annual family vacation.",
    status: "APPROVED",
    approverId: "emp-aditi",
    approverComment: "Approved.",
    appliedAt: "2026-03-02T09:00:00.000Z",
    decidedAt: "2026-03-04T16:00:00.000Z",
  },
  {
    id: "lr-12",
    referenceNumber: "LR-2026-0012",
    employeeId: "emp-sana",
    leaveTypeId: "lt-sick",
    startDate: "2026-04-06",
    endDate: "2026-04-07",
    days: 2,
    reason: "Recovering from a minor procedure.",
    status: "APPROVED",
    approverId: "emp-neha",
    approverComment: "Take care, approved.",
    appliedAt: "2026-04-05T18:00:00.000Z",
    decidedAt: "2026-04-06T08:00:00.000Z",
  },
  {
    id: "lr-13",
    referenceNumber: "LR-2026-0013",
    employeeId: "emp-arjun",
    leaveTypeId: "lt-casual",
    startDate: "2026-04-21",
    endDate: "2026-04-21",
    days: 1,
    reason: "Personal errand.",
    status: "APPROVED",
    approverId: "emp-neha",
    approverComment: "Approved.",
    appliedAt: "2026-04-17T13:00:00.000Z",
    decidedAt: "2026-04-17T15:20:00.000Z",
  },
  {
    id: "lr-14",
    referenceNumber: "LR-2026-0014",
    employeeId: "emp-vikram",
    leaveTypeId: "lt-casual",
    startDate: "2026-05-04",
    endDate: "2026-05-05",
    days: 2,
    reason: "Moving apartments.",
    status: "APPROVED",
    approverId: "emp-priya",
    approverComment: "Approved, good luck with the move.",
    appliedAt: "2026-04-27T09:00:00.000Z",
    decidedAt: "2026-04-29T11:00:00.000Z",
  },
  {
    id: "lr-15",
    referenceNumber: "LR-2026-0015",
    employeeId: "emp-priya",
    leaveTypeId: "lt-wfh",
    startDate: "2026-05-18",
    endDate: "2026-05-20",
    days: 3,
    reason: "Working remote while ISP fixes wiring at home.",
    status: "APPROVED",
    approverId: "emp-aditi",
    approverComment: "Approved.",
    appliedAt: "2026-05-15T10:00:00.000Z",
    decidedAt: "2026-05-15T14:30:00.000Z",
  },
  {
    id: "lr-16",
    referenceNumber: "LR-2026-0016",
    employeeId: "emp-rahul",
    leaveTypeId: "lt-wfh",
    startDate: "2026-05-11",
    endDate: "2026-05-13",
    days: 3,
    reason: "Would like to work from hometown for a family event.",
    status: "REJECTED",
    approverId: "emp-neha",
    approverComment: "Sprint deadline that week — please reschedule.",
    appliedAt: "2026-05-04T09:00:00.000Z",
    decidedAt: "2026-05-05T10:00:00.000Z",
  },
  {
    id: "lr-17",
    referenceNumber: "LR-2026-0017",
    employeeId: "emp-sana",
    leaveTypeId: "lt-earned",
    startDate: "2026-06-08",
    endDate: "2026-06-12",
    days: 5,
    reason: "Trip to see family.",
    status: "APPROVED",
    approverId: "emp-neha",
    approverComment: "Approved.",
    appliedAt: "2026-05-25T09:00:00.000Z",
    decidedAt: "2026-05-27T12:00:00.000Z",
  },
  {
    id: "lr-18",
    referenceNumber: "LR-2026-0018",
    employeeId: "emp-rahul",
    leaveTypeId: "lt-sick",
    startDate: "2026-06-23",
    endDate: "2026-06-23",
    days: 1,
    reason: "Viral fever.",
    status: "APPROVED",
    approverId: "emp-neha",
    approverComment: "Get well soon.",
    appliedAt: "2026-06-23T07:30:00.000Z",
    decidedAt: "2026-06-23T08:00:00.000Z",
  },
  {
    id: "lr-19",
    referenceNumber: "LR-2026-0019",
    employeeId: "emp-vikram",
    leaveTypeId: "lt-earned",
    startDate: "2026-07-13",
    endDate: "2026-07-14",
    days: 2,
    reason: "Long weekend trip.",
    status: "APPROVED",
    approverId: "emp-priya",
    approverComment: "Approved.",
    appliedAt: "2026-07-06T09:00:00.000Z",
    decidedAt: "2026-07-07T09:45:00.000Z",
  },
  {
    id: "lr-20",
    referenceNumber: "LR-2026-0020",
    employeeId: "emp-neha",
    leaveTypeId: "lt-casual",
    startDate: "2026-07-27",
    endDate: "2026-07-27",
    days: 1,
    reason: "Doctor's appointment.",
    status: "APPROVED",
    approverId: "emp-aditi",
    approverComment: "Approved.",
    appliedAt: "2026-07-24T11:00:00.000Z",
    decidedAt: "2026-07-24T13:10:00.000Z",
  },
];

// ---- Onboarding ----

const ONBOARDING_CREATED_AT = "2026-01-05T09:00:00.000Z";

export const onboardingResources: OnboardingResource[] = [
  {
    id: "res-handbook",
    title: "Employee Handbook",
    category: "POLICY",
    description: "The company-wide policies every employee should know — leave, working hours, expenses, and conduct.",
    content:
      "Welcome to Agrileaf! This handbook covers working hours (flexible, core hours 11am–4pm), expense reimbursement (submit within 30 days via Finance), " +
      "and our leave policy (see the Leave module for your balances). Please read this in full during your first week.",
    url: null,
    status: "PUBLISHED",
    isRequired: true,
    audienceScope: "ALL",
    audienceDepartmentId: null,
    audienceRole: null,
    effectiveDate: null,
    version: 1,
    document: null,
    attachments: [{ id: "att-handbook-pdf", name: "Employee Handbook (PDF)", url: "https://example.com/files/employee-handbook.pdf" }],
    createdAt: ONBOARDING_CREATED_AT,
  },
  {
    id: "res-conduct",
    title: "Code of Conduct",
    category: "POLICY",
    description: "Our expectations around workplace behavior, anti-harassment, and conflicts of interest.",
    content:
      "We expect every team member to treat colleagues, customers, and partners with respect. Harassment or discrimination of any kind will not be tolerated. " +
      "If you have a conflict of interest (e.g. a family member at a vendor), disclose it to HR. Report concerns confidentially to peopleops@agrileaf.in.",
    url: null,
    status: "PUBLISHED",
    isRequired: true,
    audienceScope: "ALL",
    audienceDepartmentId: null,
    audienceRole: null,
    effectiveDate: null,
    version: 1,
    document: null,
    attachments: [],
    createdAt: ONBOARDING_CREATED_AT,
  },
  {
    id: "res-workstation",
    title: "Setting Up Your Workstation",
    category: "GUIDE",
    description: "Step-by-step guide to getting your laptop, accounts, and dev environment ready.",
    content:
      "1. Your laptop and login credentials are provisioned by IT before day one. 2. Install the required tools from the internal software catalog. " +
      "3. Request access to team repositories via your manager. 4. Set up two-factor authentication on your company accounts.",
    url: null,
    status: "PUBLISHED",
    isRequired: true,
    audienceScope: "DEPARTMENT",
    audienceDepartmentId: "dept-eng",
    audienceRole: null,
    effectiveDate: null,
    version: 1,
    document: null,
    attachments: [{ id: "att-workstation-catalog", name: "Software catalog", url: "https://example.com/it/software-catalog" }],
    createdAt: ONBOARDING_CREATED_AT,
  },
  {
    id: "res-security",
    title: "Security Awareness Training",
    category: "TRAINING",
    description: "A short course on phishing, password hygiene, and data handling.",
    content:
      "This training covers how to spot phishing emails, why you should use a password manager, and how to handle customer data securely. " +
      "Watch the recording and complete the short quiz linked below.",
    url: "https://example.com/training/security-awareness",
    status: "PUBLISHED",
    isRequired: true,
    audienceScope: "ALL",
    audienceDepartmentId: null,
    audienceRole: null,
    effectiveDate: null,
    version: 1,
    document: null,
    attachments: [],
    createdAt: ONBOARDING_CREATED_AT,
  },
  {
    id: "res-benefits",
    title: "Benefits Overview",
    category: "GUIDE",
    description: "Health insurance, leave entitlements, and other perks available to you.",
    content:
      "Agrileaf covers group health insurance for you and your dependents from day one. See the Leave module for your annual leave entitlements. " +
      "Ask HR about the annual learning stipend and remote-work equipment allowance.",
    url: null,
    status: "PUBLISHED",
    isRequired: false,
    audienceScope: "ALL",
    audienceDepartmentId: null,
    audienceRole: null,
    effectiveDate: null,
    version: 1,
    document: null,
    attachments: [],
    createdAt: ONBOARDING_CREATED_AT,
  },
  {
    id: "res-manager-playbook",
    title: "New Manager Playbook",
    category: "GUIDE",
    description: "How to run your first 1:1s, approve leave, and set expectations with your team.",
    content:
      "As a manager, you're responsible for approving your direct reports' leave requests in My Approvals and keeping an eye on their onboarding progress. " +
      "Schedule a weekly 1:1 with each report during their first month, and review the Team Calendar before approving time off that overlaps with deadlines.",
    url: null,
    status: "PUBLISHED",
    isRequired: true,
    audienceScope: "ROLE",
    audienceDepartmentId: null,
    audienceRole: "MANAGER",
    effectiveDate: null,
    version: 1,
    document: null,
    attachments: [],
    createdAt: ONBOARDING_CREATED_AT,
  },
  {
    id: "res-remote-work-policy",
    title: "Remote Work Policy",
    category: "POLICY",
    description: "Draft policy covering hybrid schedules and home-office stipends — pending leadership sign-off.",
    content: "Draft: employees may work remotely up to 3 days per week, subject to manager approval. Final terms are still under review with leadership.",
    url: null,
    status: "DRAFT",
    isRequired: false,
    audienceScope: "ALL",
    audienceDepartmentId: null,
    audienceRole: null,
    effectiveDate: null,
    version: 1,
    document: null,
    attachments: [],
    createdAt: ONBOARDING_CREATED_AT,
  },
  {
    id: "res-benefits-update",
    title: "2026 Open Enrollment Guide",
    category: "GUIDE",
    description: "What's changing in this year's benefits enrollment window, and how to make your elections.",
    content: "Open enrollment runs for two weeks starting on the effective date below. Review your current elections and submit any changes through the HR portal.",
    url: null,
    status: "PUBLISHED",
    isRequired: false,
    audienceScope: "ALL",
    audienceDepartmentId: null,
    audienceRole: null,
    effectiveDate: "2026-09-01",
    version: 1,
    document: null,
    attachments: [],
    createdAt: ONBOARDING_CREATED_AT,
  },
];

export const onboardingChecklists: OnboardingChecklist[] = [
  { id: "checklist-eng", name: "Engineering Onboarding", description: "Everything a new engineer needs in their first two weeks.", isActive: true },
  { id: "checklist-sales", name: "Sales Onboarding", description: "Get up to speed on process, tools, and the customer-facing playbook.", isActive: true },
];

export const onboardingTasks: OnboardingTask[] = [
  { id: "task-eng-1", checklistId: "checklist-eng", title: "Read the Employee Handbook", description: null, resourceId: "res-handbook", sortOrder: 0 },
  { id: "task-eng-2", checklistId: "checklist-eng", title: "Acknowledge the Code of Conduct", description: null, resourceId: "res-conduct", sortOrder: 1 },
  {
    id: "task-eng-3",
    checklistId: "checklist-eng",
    title: "Set up your development environment",
    description: null,
    resourceId: "res-workstation",
    sortOrder: 2,
  },
  {
    id: "task-eng-4",
    checklistId: "checklist-eng",
    title: "Complete Security Awareness Training",
    description: null,
    resourceId: "res-security",
    sortOrder: 3,
  },
  {
    id: "task-eng-5",
    checklistId: "checklist-eng",
    title: "Meet your onboarding buddy",
    description: "Grab 30 minutes with the teammate your manager introduced you to.",
    resourceId: null,
    sortOrder: 4,
  },
  {
    id: "task-eng-6",
    checklistId: "checklist-eng",
    title: "Schedule a 1:1 with your manager",
    description: "Set up a recurring weekly check-in for your first month.",
    resourceId: null,
    sortOrder: 5,
  },
  { id: "task-sales-1", checklistId: "checklist-sales", title: "Read the Employee Handbook", description: null, resourceId: "res-handbook", sortOrder: 0 },
  { id: "task-sales-2", checklistId: "checklist-sales", title: "Acknowledge the Code of Conduct", description: null, resourceId: "res-conduct", sortOrder: 1 },
  { id: "task-sales-3", checklistId: "checklist-sales", title: "Review Benefits Overview", description: null, resourceId: "res-benefits", sortOrder: 2 },
  {
    id: "task-sales-4",
    checklistId: "checklist-sales",
    title: "Set up CRM access",
    description: "Ask your manager to grant you access to the CRM and dialer.",
    resourceId: null,
    sortOrder: 3,
  },
  {
    id: "task-sales-5",
    checklistId: "checklist-sales",
    title: "Shadow a client call",
    description: "Join a live call with a teammate before running your own.",
    resourceId: null,
    sortOrder: 4,
  },
];

/** Demo progress: Vikram (Sales) is partway through onboarding; Arjun (Engineering) hasn't started. */
export const onboardingTaskCompletions: { employeeId: string; taskId: string; completedAt: string }[] = [
  { employeeId: "emp-vikram", taskId: "task-sales-1", completedAt: "2026-06-02T10:00:00.000Z" },
  { employeeId: "emp-vikram", taskId: "task-sales-2", completedAt: "2026-06-02T10:15:00.000Z" },
  { employeeId: "emp-vikram", taskId: "task-sales-3", completedAt: "2026-06-03T09:30:00.000Z" },
];
