# Generated by Django 5.1.4 on 2026-08-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(default='#16a34a', max_length=7)),
                ('default_days_per_year', models.PositiveIntegerField(default=0)),
                ('requires_approval', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accrual_method', models.CharField(choices=[('ANNUAL', 'Annual'), ('MONTHLY', 'Monthly')], default='ANNUAL', max_length=10)),
                ('carry_forward_limit', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
